sudo: required
dist: trusty
git:
  depth: 1
language: node_js
node_js:
- '6'
- '7'
- stable
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
matrix:
  fast_finish: true
install:
- npm install
before_script:
- export DBUS_SESSION_BUS_ADDRESS=/dev/null
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- npm run test:ci
- echo $TRAVIS_BRANCH
- if [ $TRAVIS_BRANCH = 'develop' ]; then npm run build:ci https://s3-us-west-1.amazonaws.com/recipe-stage-client.blendtec.com/
  --base-href /pages/stage-recipes/; fi
- if [ $TRAVIS_BRANCH = 'master' ]; then npm run build:ci https://s3-us-west-1.amazonaws.com/recipe-client.blendtec.com/
  --base-href /pages/recipe-test/; fi
after_success:
- "./node_modules/.bin/codecov"
notifications:
  slack: blendtec:a5Z5i4z3iuWbHHDdlMRSMkiB
env:
  matrix:
    secure: eztul/FDnCE3kwKI0ZUJd37QFeALAAVNhWi6aDGBL5JFae5PsrucC99xAN3sMzIqF1ssdgdCSk/n0CMuMxFAWRe+YIr6eQSRIVdxb2JRky+pSwj05dCXQ+YUvcc1P+xabuCJtgCtE0XgCvGVR8tVRsFovw8m/xWmGQ68uexekeEy4FC0B2jsCbnbxQLwCGa4Lcf/9uZcoJUnlxUlLKwv7xcoS/3zUyYzxA9n9t+rkloCHM4tS+lZhy8xyupotsh2uaxIS9dwHdnOl+vzuQertmO1RUFP5rGjHnf7PG37huJ2lqMUffUNJuOrhXS4qJkopvhmThWtNOBKbRyzCJc7hD2JvQnjM7qgpf3oCWwhbanhamaW4dtKJ4UD/sDQITt4phq6MVB5uH/RRODpSlECYdVSbno6ATYadviys5KLb4/ihqyfgWNIvn/nU1O5Wfx3JuvTS9PvW+Esq+lXyRHrPBd95Fmd7G9fE/asQMseMTS/iQp857KpNfwEgnXN5aeeQUmPVXtlyTopHg50+OsQn9GbQCy8y0GFIZoujnHJzp8+PpZ0aXPk+2UuMAUF0/I24RUW4yeQFWVU771w2O9st1MFS4+Ps5KnKilapQsJACSo8IGl4huet+eJDlDhDOWIItwFW/zmmj3buyjAQzadGOXhhkryK0IMghkwoDiIH8I=
deploy:
- provider: s3
  region: us-west-1
  access_key_id: AKIAIBSHRO4SOJ5PIBSQ
  secret_access_key:
    secure: Il9zk3MOxurkDplYAZR5nIb8UwLD1EKc7m8ZMsrOcFU6R8aKhqfQAi02lIPZMgfdFCA+ll3aU3ENRahMhQWsNRL3zmINimaVkTrv91P6Zhp3CvT/fWRTHrKXgUrawI18NOmHEZaoUPY5SWYR2D89ljdf293gRtStmnjU9JdH3HOuDXaAcZ1j5p/oEn8gumn1mZHc2ajJm5RbhqGgtNCiEqP5g/0stKoio8BilHa6yDa/khiSjeVEUb9Os7rP5bumk0IXzALi9noYbCKElJ4JOP+81m9V/zEL5XKrFpT0z5HAwma15lSxdTjh+rO2a+6u0CK/JLuatf1tpz6P3sbHDYKOzDsdsz51DN+XeiLtPn5KE4zqwkWWA2iBzyJIj0OzU110szRYRootOyaitheFjhfrAHwFMaXLzT77/gFhpXPdCjfP7BM02uuUEIATMYZ0uQlrJYkroJh7FXVeixIeQBdno8hvLWV/GY2wAJbG1B0qq7TZ0Mn7fBtVaMdo7lP0kpqn0YCwAuMkGaXskxq/2c1Zg8sPQ6SW1QsrXCifgKjsxRlmK+LDDDbRRK8eWRpbvKVEoGKZ+aglWpJXvx8TS+3k1DpCI0Cj8Iu2Pe11i6TnC+EUULF9rQic+fiHaU1ghpc7UoUaXvRApWRzowxJJHCkTzyF9yNgypYivPFsPbc=
  bucket: recipe-client.blendtec.com
  local-dir: dist
  skip_cleanup: true
  acl: public_read
  on:
    branch: master
- provider: script
  skip_cleanup: true
  script: "./.travis/deploy.sh"
  on:
    branch: master
- provider: s3
  region: us-west-1
  access_key_id: AKIAIBSHRO4SOJ5PIBSQ
  secret_access_key:
    secure: Il9zk3MOxurkDplYAZR5nIb8UwLD1EKc7m8ZMsrOcFU6R8aKhqfQAi02lIPZMgfdFCA+ll3aU3ENRahMhQWsNRL3zmINimaVkTrv91P6Zhp3CvT/fWRTHrKXgUrawI18NOmHEZaoUPY5SWYR2D89ljdf293gRtStmnjU9JdH3HOuDXaAcZ1j5p/oEn8gumn1mZHc2ajJm5RbhqGgtNCiEqP5g/0stKoio8BilHa6yDa/khiSjeVEUb9Os7rP5bumk0IXzALi9noYbCKElJ4JOP+81m9V/zEL5XKrFpT0z5HAwma15lSxdTjh+rO2a+6u0CK/JLuatf1tpz6P3sbHDYKOzDsdsz51DN+XeiLtPn5KE4zqwkWWA2iBzyJIj0OzU110szRYRootOyaitheFjhfrAHwFMaXLzT77/gFhpXPdCjfP7BM02uuUEIATMYZ0uQlrJYkroJh7FXVeixIeQBdno8hvLWV/GY2wAJbG1B0qq7TZ0Mn7fBtVaMdo7lP0kpqn0YCwAuMkGaXskxq/2c1Zg8sPQ6SW1QsrXCifgKjsxRlmK+LDDDbRRK8eWRpbvKVEoGKZ+aglWpJXvx8TS+3k1DpCI0Cj8Iu2Pe11i6TnC+EUULF9rQic+fiHaU1ghpc7UoUaXvRApWRzowxJJHCkTzyF9yNgypYivPFsPbc=
  bucket: recipe-stage-client.blendtec.com
  local-dir: dist
  skip_cleanup: true
  acl: public_read
  on:
    branch: develop
- provider: script
  skip_cleanup: true
  script: "./.travis/deploy_stage.sh"
  on:
    branch: develop
