sudo: required
dist: trusty
git:
  depth: 1
language: node_js
node_js:
- '6'
- '7'
- stable
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
matrix:
  fast_finish: true
install:
- npm install
before_script:
- export DBUS_SESSION_BUS_ADDRESS=/dev/null
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- npm run test:ci
- echo $TRAVIS_BRANCH
- if [ $TRAVIS_BRANCH = 'develop' ]; then npm run build:ci https://s3-us-west-1.amazonaws.com/recipe-stage-client.blendtec.com/
  --base-href /pages/stage-recipes/; fi
- if [ $TRAVIS_BRANCH = 'master' ]; then npm run build:ci https://s3-us-west-1.amazonaws.com/recipe-client.blendtec.com/
  --base-href /pages/recipe-test/; fi
after_success:
- "./node_modules/.bin/codecov"
notifications:
  slack: blendtec:a5Z5i4z3iuWbHHDdlMRSMkiB
env:
  matrix:
    secure: geykcK9Jr4uD8Z8U+pVT1Ye1C8TIryhBx2UDnQBhnh+NnDRsa/kZZXY3by5n5fnBTtEUogxngiN0gKdjYaxHkYh5LJjj/UUmLOY99j6LkiDRmfygiTgjp5hYUyzx9my0umOVeGd/iL+WIYrJwpa5hFS0JcStKlgwgzo76wLvCRJC5jiUfukR9rsN74HiXxadi90acswy+EWqRjWKnQMpjE92u43a3p5sYQIXDSMtWxi5QE9vV2X4JO7a9x8k6hkHt3vR2DrKOQV7+qRuGeoLurFaq2VF/1SBm/dItcto3xIifRdfM/V10nLV97e7zg4vS64H61fPtBWwN5Y5ZjzfT4/rzxAGn/1RQy8TnLPHFd6plVNF6k+0/JXQaeCsa+Z5fRZSBc9la6LWofGa7lw/GHKRmQFOGJx1q0YjlHiaxneJ3yEvQuU29BRlekzy2V4rw8PWeKvk6kdjd+oXgoaHM92QKKLePH+BmCOBF7Def+JKCr1I41aIqWYRGCa1qGUFsWJwsVAHx6Vqc/6mHBuAGNRydr8yqpdD91WcJ4HF0F3zWgbnjIQiDEbr/YJa2Tbf2kUnJ3LLiFdJwoKv5Nbt6bTRlqnLdLDgSBiC3b7Gq5MqDua/XJzMhm6RozZXLs7RH9wRajW52QkZpaAoAAOoWSNON0DAgY5ICDUlkgGF7rM=
deploy:
- provider: s3
  region: us-west-1
  access_key_id: AKIAIBSHRO4SOJ5PIBSQ
  secret_access_key:
    secure: Il9zk3MOxurkDplYAZR5nIb8UwLD1EKc7m8ZMsrOcFU6R8aKhqfQAi02lIPZMgfdFCA+ll3aU3ENRahMhQWsNRL3zmINimaVkTrv91P6Zhp3CvT/fWRTHrKXgUrawI18NOmHEZaoUPY5SWYR2D89ljdf293gRtStmnjU9JdH3HOuDXaAcZ1j5p/oEn8gumn1mZHc2ajJm5RbhqGgtNCiEqP5g/0stKoio8BilHa6yDa/khiSjeVEUb9Os7rP5bumk0IXzALi9noYbCKElJ4JOP+81m9V/zEL5XKrFpT0z5HAwma15lSxdTjh+rO2a+6u0CK/JLuatf1tpz6P3sbHDYKOzDsdsz51DN+XeiLtPn5KE4zqwkWWA2iBzyJIj0OzU110szRYRootOyaitheFjhfrAHwFMaXLzT77/gFhpXPdCjfP7BM02uuUEIATMYZ0uQlrJYkroJh7FXVeixIeQBdno8hvLWV/GY2wAJbG1B0qq7TZ0Mn7fBtVaMdo7lP0kpqn0YCwAuMkGaXskxq/2c1Zg8sPQ6SW1QsrXCifgKjsxRlmK+LDDDbRRK8eWRpbvKVEoGKZ+aglWpJXvx8TS+3k1DpCI0Cj8Iu2Pe11i6TnC+EUULF9rQic+fiHaU1ghpc7UoUaXvRApWRzowxJJHCkTzyF9yNgypYivPFsPbc=
  bucket: recipe-client.blendtec.com
  local-dir: dist
  skip_cleanup: true
  acl: public_read
  on:
    branch: master
- provider: script
  skip_cleanup: true
  script: "./.travis/deploy.sh"
  on:
    branch: master
- provider: s3
  region: us-west-1
  access_key_id: AKIAIBSHRO4SOJ5PIBSQ
  secret_access_key:
    secure: Il9zk3MOxurkDplYAZR5nIb8UwLD1EKc7m8ZMsrOcFU6R8aKhqfQAi02lIPZMgfdFCA+ll3aU3ENRahMhQWsNRL3zmINimaVkTrv91P6Zhp3CvT/fWRTHrKXgUrawI18NOmHEZaoUPY5SWYR2D89ljdf293gRtStmnjU9JdH3HOuDXaAcZ1j5p/oEn8gumn1mZHc2ajJm5RbhqGgtNCiEqP5g/0stKoio8BilHa6yDa/khiSjeVEUb9Os7rP5bumk0IXzALi9noYbCKElJ4JOP+81m9V/zEL5XKrFpT0z5HAwma15lSxdTjh+rO2a+6u0CK/JLuatf1tpz6P3sbHDYKOzDsdsz51DN+XeiLtPn5KE4zqwkWWA2iBzyJIj0OzU110szRYRootOyaitheFjhfrAHwFMaXLzT77/gFhpXPdCjfP7BM02uuUEIATMYZ0uQlrJYkroJh7FXVeixIeQBdno8hvLWV/GY2wAJbG1B0qq7TZ0Mn7fBtVaMdo7lP0kpqn0YCwAuMkGaXskxq/2c1Zg8sPQ6SW1QsrXCifgKjsxRlmK+LDDDbRRK8eWRpbvKVEoGKZ+aglWpJXvx8TS+3k1DpCI0Cj8Iu2Pe11i6TnC+EUULF9rQic+fiHaU1ghpc7UoUaXvRApWRzowxJJHCkTzyF9yNgypYivPFsPbc=
  bucket: recipe-stage-client.blendtec.com
  local-dir: dist
  skip_cleanup: true
  acl: public_read
  on:
    branch: develop
- provider: script
  skip_cleanup: true
  script: "./.travis/deploy_stage.sh"
  on:
    branch: develop
