sudo: required
dist: trusty
git:
  depth: 1
language: node_js
node_js:
- '6'
- '7'
- stable
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
matrix:
  fast_finish: true
install:
- npm install
before_script:
- export DBUS_SESSION_BUS_ADDRESS=/dev/null
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- npm run test:ci
- echo $TRAVIS_BRANCH
- if [ $TRAVIS_BRANCH = 'develop' ]; then npm run build:ci https://s3-us-west-1.amazonaws.com/recipe-stage-client.blendtec.com/registration/
  --base-href /pages/stage-recipes/; fi
- if [ $TRAVIS_BRANCH = 'master' ]; then npm run build:ci https://s3-us-west-1.amazonaws.com/recipe-client.blendtec.com/registration/
  --base-href /pages/recipe-test/; fi
after_success:
- "./node_modules/.bin/codecov"
notifications:
  slack: blendtec:a5Z5i4z3iuWbHHDdlMRSMkiB
env:
  global:
  - secure: LXyCRkksnLq4bWx8H3B1v+uSl10Xk8Jl0PNw3tG1CNhq3K8B95BNZJ8a3EW8LW4mSnMllRAbMzE3U/cGS+x1AWCN3tdbWwRoBdaMN60qaEZScamHVDDbFde/iDooEtjDkTn9CF2P0F8/RUf+m7q+y3zVo8Y8JlMMFKQa8L0IC9gjlZnp8pqjmadMM0l9NUnSjvB3JWoc0AOuBdWrbW4ZM9cZTQbor2wqJCNiQ/7uoXuP4Zuc7bVJjlgHcWUMsoEzz/h/vUPu6v1rPmfJ50rqYphug3WqOvFr4FCFbxIRHn7J0GAybH0gBa/IBLGA89uriVEK4Yye8aZieIbKc0cgRYu9E2+aqobHGRw1uHzquTn7y76jNEcVkY9uqs9v3qYJ7eGglabOINOlxearET0DxQ/YJAsdBZwBNvscYn2o2HJo0kaIPi7BL+MrdP6wbZnNOfV3WcQ/YCPZVCdHpsFBw2OaQ77Cuy4qDUHNZisKg6SJfSdBHUMNMxZ59rrxL4bvMtWlmQNt2QZdfiwcPHQf9jxXmsvBJp2r+AyfL2gAGx4VidiWZUMtlo3ZT5aUJe8/Hmd+37fbyyYyLluBuWjRMya5knn0AZ95XoWTasrGySHDPPpvl1cxXFIh0m8ASM0MtCKGG/Y6xwAmk3QDtiBaqkxNlgl44fQhtGrSZuL8A4c=
  - secure: BFxp3MO8gtBTxRWRMXajra8zCQJ9P2JOcZ7eqVmI3yzSYzGAIpX2D32zWxSe0HLDssz5v8kJTTP4jfvteDdSDFFosg39RMyJYioDYzaSS4rwf4mpM4KTMnOoogc3aCuWfMgXDjNn5Hql/Qj0mCu092fvUBV4bx++zpK1FDjb5g4JV3zPup/8ITpA+eyfgB8uLedFNmHgD70Qgy2iLNqzafIbW+30vsLhAWXkcetyDJOfNspxamPSLZrVM3vCtDbVHZaFzpmsTnwpHLMIAGqvR1jkNIa1ABNOc4Lyfeo0s+PawOn8BjkUvO3BzEiBirnr8SQc4U6VDtk0G0kHYzWYhtE2+IAUILVMmoKYLv3orlZdv98Ix5N/aGsbP+6UNcfUXaCsHjzE/0WekgK/TVRA+kh8RSbw+ZtxI8Y5iwQC4zCNRNh+AJZ0aAgMPiCZEq4FYm//ofyboARUmrZleCMPa+C5Z2oUWnpNxZWCjiEwGiuweICT2fhZSrwzJPrbBf0lgGylBry7Qae0pCJEvlRmyQnG0Kuo1FXORG/iG4tYAd96/jAqIN2NjIPcIaBrLl4rsARX1U6WsGZOrCJreLOb6ABwHms6p3cJbu0KlEaTYumsKVGxLJBEdqZf3lndSUb6UD0jtE9C18J2o0bSkDZqwmAKaXhGHmB6K+MVPAJ1k6I=
deploy:
- provider: s3
  region: us-west-1
  access_key_id: AKIAIBSHRO4SOJ5PIBSQ
  secret_access_key:
    secure: Il9zk3MOxurkDplYAZR5nIb8UwLD1EKc7m8ZMsrOcFU6R8aKhqfQAi02lIPZMgfdFCA+ll3aU3ENRahMhQWsNRL3zmINimaVkTrv91P6Zhp3CvT/fWRTHrKXgUrawI18NOmHEZaoUPY5SWYR2D89ljdf293gRtStmnjU9JdH3HOuDXaAcZ1j5p/oEn8gumn1mZHc2ajJm5RbhqGgtNCiEqP5g/0stKoio8BilHa6yDa/khiSjeVEUb9Os7rP5bumk0IXzALi9noYbCKElJ4JOP+81m9V/zEL5XKrFpT0z5HAwma15lSxdTjh+rO2a+6u0CK/JLuatf1tpz6P3sbHDYKOzDsdsz51DN+XeiLtPn5KE4zqwkWWA2iBzyJIj0OzU110szRYRootOyaitheFjhfrAHwFMaXLzT77/gFhpXPdCjfP7BM02uuUEIATMYZ0uQlrJYkroJh7FXVeixIeQBdno8hvLWV/GY2wAJbG1B0qq7TZ0Mn7fBtVaMdo7lP0kpqn0YCwAuMkGaXskxq/2c1Zg8sPQ6SW1QsrXCifgKjsxRlmK+LDDDbRRK8eWRpbvKVEoGKZ+aglWpJXvx8TS+3k1DpCI0Cj8Iu2Pe11i6TnC+EUULF9rQic+fiHaU1ghpc7UoUaXvRApWRzowxJJHCkTzyF9yNgypYivPFsPbc=
  bucket: recipe-client.blendtec.com
  local-dir: dist
  skip_cleanup: true
  acl: public_read
  on:
    branch: master
- provider: script
  skip_cleanup: true
  script: "./.travis/deploy.sh"
  on:
    branch: master
- provider: s3
  region: us-west-1
  access_key_id: AKIAIBSHRO4SOJ5PIBSQ
  secret_access_key:
    secure: Il9zk3MOxurkDplYAZR5nIb8UwLD1EKc7m8ZMsrOcFU6R8aKhqfQAi02lIPZMgfdFCA+ll3aU3ENRahMhQWsNRL3zmINimaVkTrv91P6Zhp3CvT/fWRTHrKXgUrawI18NOmHEZaoUPY5SWYR2D89ljdf293gRtStmnjU9JdH3HOuDXaAcZ1j5p/oEn8gumn1mZHc2ajJm5RbhqGgtNCiEqP5g/0stKoio8BilHa6yDa/khiSjeVEUb9Os7rP5bumk0IXzALi9noYbCKElJ4JOP+81m9V/zEL5XKrFpT0z5HAwma15lSxdTjh+rO2a+6u0CK/JLuatf1tpz6P3sbHDYKOzDsdsz51DN+XeiLtPn5KE4zqwkWWA2iBzyJIj0OzU110szRYRootOyaitheFjhfrAHwFMaXLzT77/gFhpXPdCjfP7BM02uuUEIATMYZ0uQlrJYkroJh7FXVeixIeQBdno8hvLWV/GY2wAJbG1B0qq7TZ0Mn7fBtVaMdo7lP0kpqn0YCwAuMkGaXskxq/2c1Zg8sPQ6SW1QsrXCifgKjsxRlmK+LDDDbRRK8eWRpbvKVEoGKZ+aglWpJXvx8TS+3k1DpCI0Cj8Iu2Pe11i6TnC+EUULF9rQic+fiHaU1ghpc7UoUaXvRApWRzowxJJHCkTzyF9yNgypYivPFsPbc=
  bucket: recipe-stage-client.blendtec.com
  local-dir: dist
  skip_cleanup: true
  acl: public_read
  on:
    branch: develop
- provider: script
  skip_cleanup: true
  script: "./.travis/deploy_stage.sh"
  on:
    branch: develop
